//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guidelines.WebUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Guidelines.WebUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied!.
        /// </summary>
        public static string Error_AccessDenied {
            get {
                return ResourceManager.GetString("Error_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller not derived from base..
        /// </summary>
        public static string Error_ControllerNotDerivedFromBase {
            get {
                return ResourceManager.GetString("Error_ControllerNotDerivedFromBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input not in the correct format..
        /// </summary>
        public static string Error_InputNotInTheCorrectFormat {
            get {
                return ResourceManager.GetString("Error_InputNotInTheCorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not en exception..
        /// </summary>
        public static string Error_NotAnException {
            get {
                return ResourceManager.GetString("Error_NotAnException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one typeless redirect on error per action..
        /// </summary>
        public static string Error_OnlyOneTypelessRedirectOnErrorPerAction {
            get {
                return ResourceManager.GetString("Error_OnlyOneTypelessRedirectOnErrorPerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect Url Must Have Value.
        /// </summary>
        public static string Error_RedirectUrlMustHaveValue {
            get {
                return ResourceManager.GetString("Error_RedirectUrlMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread abort cannot be caught..
        /// </summary>
        public static string Error_ThreadAbortCantBeCaught {
            get {
                return ResourceManager.GetString("Error_ThreadAbortCantBeCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url is empty..
        /// </summary>
        public static string Error_UrlIsEmpty {
            get {
                return ResourceManager.GetString("Error_UrlIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        public static string Error_ValidationError {
            get {
                return ResourceManager.GetString("Error_ValidationError", resourceCulture);
            }
        }
    }
}
